---

name: 🐞 Bug Report
description: Create a report to help us improve.
labels:
- bug
body:
- type: markdown
  attributes:
    value: |
      **Thanks for taking a minute to file a bug report!**

      > [!warning]
      > Verify first that your issue is not [already reported on
      > GitHub][issue search].

      _Please fill out the form below with as many precise
      details as possible._

      [issue search]: ../search?q=is%3Aissue&type=issues

- type: checkboxes
  id: terms
  attributes:
    label: Please confirm the following
    description: |
      Read the [Code of Conduct][CoC] first. Check the existing issues
      on the tracker. Take into account the possibility of your report
      surfacing a security vulnerability.

      [CoC]: ../blob/main/.github/CODE_OF_CONDUCT.md
    options:
    - label: |
        I agree to follow the [Code of Conduct][CoC].

        [CoC]: ../blob/main/.github/CODE_OF_CONDUCT.md
      required: true
    - label: |
        I have checked the [current issues][issue search] for
        duplicates.

        [issue search]: ../search?q=is%3Aissue&type=issues
      required: true
    - label: >-
        I understand this is open source software provided for free
        and that I might not receive a timely response.
      required: true
    - label: |
        I am positive I am **NOT** reporting a (potential) security
        vulnerability, to the best of my knowledge. _(These must be
        shared by submitting [this report form][vulnerability report
        form] instead, if any hesitation exists.)_

        [vulnerability report form]: ../security/advisories/new
      required: true
    - label: >-
        I am willing to submit a pull request with reproducers as
        xfailing test cases or even an entire fix. _(Assign this
        issue to me.)_
      required: false

- type: textarea
  attributes:
    label: Describe the bug
    description: >-
      A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  attributes:
    label: To Reproduce
    description: >-
      Describe the steps to reproduce this bug.
    placeholder: |
      1. Configure a tox project as follows...
      2. Run `tox run -e ...`
      3. See the unexpected behavior described below.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: >-
      A clear and concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Logs / tracebacks
    description: |
      If applicable, add logs/tracebacks to help explain your problem.
      Paste the output of the commands above, including the commands
      themselves and their output/traceback etc.
    render: python-traceback
  validations:
    required: true

- type: textarea
  attributes:
    label: Python version
    description: Attach the output of `python --version`.
    render: console
    value: |
      $ python --version
  validations:
    required: true

- type: textarea
  attributes:
    label: tox version
    description: Attach the output of `python -m pip show tox`.
    render: console
    value: |
      $ python -m pip show tox
  validations:
    required: true

- type: textarea
  attributes:
    label: tox-towncrier version
    description: Attach the output of `python -m pip show tox-towncrier`.
    render: console
    value: |
      $ python -m pip show tox-towncrier
  validations:
    required: true

- type: textarea
  attributes:
    label: OS
    placeholder: >-
      For example, Arch Linux, Windows, macOS, etc.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context about the problem here. Describe the
      environment you have that lead to your issue. This includes
      shell configuration, virtualenv setup, CI specifics that are
      related to your case.

...
